name = "robots-massacre-web-rewrite"
main = "worker/signaling.ts"
compatibility_date = "2026-07-04"

[assets]
directory = "./dist"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomObject"]
